name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
    - uses: aws-actions/setup-sam@v1
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        dotnet-version: 6.0.x
        aws-access-key-id: AKIA4PU7ZWLALBGAPFPI
        aws-secret-access-key: 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
        aws-region: us-east-2
        
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

