name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

#defaults:
#  run:
#    working-directory: aws_api

jobs:
  build:

    runs-on: ubuntu-latest
    env:
#      working-directory: aws_api
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: AWS CLI
        run: dotnet tool install -g Amazon.Lambda.Tools
      - name: Restore dependencies
        working-directory: aws_api
        run: dotnet restore
      - name: Build
        working-directory: aws_api
        run: dotnet build --no-restore
      - name: Deploy to Lambda
        working-directory: aws_api
        run: dotnet lambda deploy-serverless
